### ISSUE TITLE
Need Guidance regarding making our own actual distro 

### ISSUE THREAD

**Issue by anonfaded** [nir9/welcome#1]
Hey 👋🏻
I hope you'll be doing good. I saw your YouTube tutorial and i want some guidance from someone experienced so i can do it better, i hope you'll give me your few minutes:)

So I wanna make my own linux distro designed for Pentesters with custom tools and any data that i want to add into it, with custom boot loading logos and all like the official ones. I like the ubuntu-desktop gui on ubuntu so i want that as the gui but I'm not sure from where to start and what knowledge should i first get before starting, and that should get all the updates automatically just like normal distros without my interactions as i just want to make it one time with custom design and tools and i don't want a constant effort of releasing updates every week. 

So can you share the resources or topics in points which should i learn and how to start work on this, like complete guidance as i never did something like this...
Waiting for your reply here as in YouTube comments there are so many comments where its not easy to answer 🙂

**Comment by nir9** [comment]
A good starting point is to check out debootstrap which is a tool that can help you install a debian/ubuntu base system, more info at https://wiki.debian.org/Debootstrap

This is an interesting topic and I'll consider this for a future video :)
